"""add_admin_tables_and_api_log_columns

Revision ID: 219d3a207b8f
Revises: f845e7366b43
Create Date: 2026-07-29 13:24:01.033491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219d3a207b8f'
down_revision: Union[str, None] = 'f845e7366b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_otps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_otps_email'), 'admin_otps', ['email'], unique=False)
    op.create_table('admin_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_sessions_email'), 'admin_sessions', ['email'], unique=False)
    op.create_index(op.f('ix_admin_sessions_token_hash'), 'admin_sessions', ['token_hash'], unique=True)
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('api_logs', sa.Column('user_agent', sa.String(length=512), nullable=True))
    op.add_column('api_logs', sa.Column('query_string', sa.Text(), nullable=True))
    op.add_column('api_logs', sa.Column('error_code', sa.String(length=50), nullable=True))
    op.alter_column('api_logs', 'endpoint',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.create_index('ix_api_logs_client_created', 'api_logs', ['client_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_api_logs_created_at'), 'api_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_logs_request_id'), 'api_logs', ['request_id'], unique=False)
    op.create_index('ix_api_logs_status_created', 'api_logs', ['status_code', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_logs_status_created', table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_request_id'), table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_created_at'), table_name='api_logs')
    op.drop_index('ix_api_logs_client_created', table_name='api_logs')
    op.alter_column('api_logs', 'endpoint',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('api_logs', 'error_code')
    op.drop_column('api_logs', 'query_string')
    op.drop_column('api_logs', 'user_agent')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_admin_sessions_token_hash'), table_name='admin_sessions')
    op.drop_index(op.f('ix_admin_sessions_email'), table_name='admin_sessions')
    op.drop_table('admin_sessions')
    op.drop_index(op.f('ix_admin_otps_email'), table_name='admin_otps')
    op.drop_table('admin_otps')
    # ### end Alembic commands ###
