"""add_cors_origins_to_api_keys

Revision ID: 41ce2d2fbf57
Revises: d736c8821797
Create Date: 2026-07-30 17:45:42.394750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ce2d2fbf57'
down_revision: Union[str, None] = 'd736c8821797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('cors_origins', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'cors_origins')
    # ### end Alembic commands ###
