"""fix_idempotency_key_unique_per_client

Revision ID: d736c8821797
Revises: a1b2c3d4e5f6
Create Date: 2026-07-29 18:17:41.324052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd736c8821797'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('scan_jobs_idempotency_key_key'), 'scan_jobs', type_='unique')
    op.create_unique_constraint('uq_scan_jobs_client_idempotency', 'scan_jobs', ['client_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_scan_jobs_client_idempotency', 'scan_jobs', type_='unique')
    op.create_unique_constraint(op.f('scan_jobs_idempotency_key_key'), 'scan_jobs', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
